[package]
name = "nu_plugin_nudo"
version = "0.1.0"
edition = "2024"

[dependencies]
nu-plugin = "0.109.1"
nu-protocol = "0.109.1"
syscalls = { version = "0.7.0", features = ["all"] }
which = "8.0.0"
